# Generated by Django 4.2.2 on 2024-03-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('m', 'M'), ('xs', 'XS'), ('xxxl', 'XXXL'), ('xxs', 'XXS'), ('xxxs', 'XXXS'), ('xxl', 'XXL'), ('l', 'L'), ('s', 'S'), ('xl', 'XL')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('ft', 'Feet'), ('in', 'Inches'), ('cm', 'CM')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('3', '3'), ('1', '1'), ('4', '4'), ('5', '5'), ('2', '2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('unshipped', 'Unshipped'), ('shipped', 'Shipped'), ('preshipment', 'Pre-shipment'), ('delivered', 'Delivered')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('free_shipping', 'Free Shipping'), ('free_express_shipping', 'Free Express Shipping'), ('free_2_day_shipping', 'Free 2 Day Shipping')], max_length=70, null=True),
        ),
    ]
