# Generated by Django 4.2.2 on 2024-03-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_productsize_size_alter_productsize_size_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xs', 'XS'), ('m', 'M'), ('s', 'S'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxs', 'XXS'), ('xxxl', 'XXXL'), ('l', 'L'), ('xxxs', 'XXXS')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('3', '3'), ('4', '4'), ('1', '1'), ('2', '2'), ('5', '5')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('unshipped', 'Unshipped'), ('preshipment', 'Pre-shipment'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('free_shipping', 'Free Shipping'), ('free_2_day_shipping', 'Free 2 Day Shipping'), ('free_express_shipping', 'Free Express Shipping')], max_length=70, null=True),
        ),
    ]
