# Generated by Django 4.2.2 on 2024-03-17 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0003_alter_productsize_size_alter_reviews_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmetas',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xxl', 'XXL'), ('xxxs', 'XXXS'), ('s', 'S'), ('xl', 'XL'), ('xs', 'XS'), ('m', 'M'), ('xxs', 'XXS'), ('xxxl', 'XXXL'), ('l', 'L')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('in', 'Inches'), ('cm', 'CM'), ('ft', 'Feet')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('3', '3'), ('5', '5'), ('1', '1'), ('4', '4'), ('2', '2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(blank=True, choices=[('published', 'Published'), ('draft', 'Draft')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('unshipped', 'Unshipped'), ('shipped', 'Shipped'), ('preshipment', 'Pre-shipment')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('free_express_shipping', 'Free Express Shipping'), ('free_shipping', 'Free Shipping'), ('free_2_day_shipping', 'Free 2 Day Shipping')], max_length=70, null=True),
        ),
    ]
