# Generated by Django 4.2.2 on 2024-03-29 09:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_productsize_size_alter_productsize_size_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xxxs', 'XXXS'), ('l', 'L'), ('xxs', 'XXS'), ('xs', 'XS'), ('xxl', 'XXL'), ('m', 'M'), ('xxxl', 'XXXL'), ('xl', 'XL'), ('s', 'S')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('in', 'Inches'), ('ft', 'Feet'), ('cm', 'CM')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('5', '5'), ('3', '3'), ('4', '4')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('preshipment', 'Pre-shipment'), ('shipped', 'Shipped'), ('unshipped', 'Unshipped'), ('delivered', 'Delivered')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('free_2_day_shipping', 'Free 2 Day Shipping'), ('free_express_shipping', 'Free Express Shipping'), ('free_shipping', 'Free Shipping')], max_length=70, null=True),
        ),
    ]
