# Generated by Django 4.2.2 on 2024-03-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_product_description_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xxl', 'XXL'), ('xxxl', 'XXXL'), ('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('xl', 'XL'), ('l', 'L'), ('xxxs', 'XXXS')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('ft', 'Feet'), ('in', 'Inches'), ('cm', 'CM')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('2', '2'), ('4', '4'), ('5', '5'), ('1', '1'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('unshipped', 'Unshipped'), ('preshipment', 'Pre-shipment')], max_length=50, null=True),
        ),
    ]
