# Generated by Django 4.2.2 on 2024-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_productsize_size_alter_productsize_size_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xs', 'XS'), ('l', 'L'), ('xxs', 'XXS'), ('s', 'S'), ('xxxl', 'XXXL'), ('xxl', 'XXL'), ('xl', 'XL'), ('m', 'M'), ('xxxs', 'XXXS')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('ft', 'Feet'), ('cm', 'CM'), ('in', 'Inches')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('4', '4'), ('1', '1'), ('2', '2'), ('3', '3'), ('5', '5')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('shipped', 'Shipped'), ('unshipped', 'Unshipped'), ('preshipment', 'Pre-shipment'), ('delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
