# Generated by Django 4.2.2 on 2024-03-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_remove_taxrate_slug_remove_taxrate_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xxxl', 'XXXL'), ('m', 'M'), ('xs', 'XS'), ('s', 'S'), ('xxs', 'XXS'), ('xxxs', 'XXXS'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('cm', 'CM'), ('ft', 'Feet'), ('in', 'Inches')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('preshipment', 'Pre-shipment'), ('delivered', 'Delivered'), ('shipped', 'Shipped'), ('unshipped', 'Unshipped')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('free_express_shipping', 'Free Express Shipping'), ('free_shipping', 'Free Shipping'), ('free_2_day_shipping', 'Free 2 Day Shipping')], max_length=70, null=True),
        ),
    ]
