# Generated by Django 4.2.2 on 2024-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_productsize_size_alter_productsize_size_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested_proccessed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xxxl', 'XXXL'), ('m', 'M'), ('xs', 'XS'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxs', 'XXS'), ('s', 'S'), ('l', 'L'), ('xxxs', 'XXXS')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('in', 'Inches'), ('ft', 'Feet'), ('cm', 'CM')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('2', '2'), ('4', '4'), ('3', '3'), ('5', '5'), ('1', '1')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(blank=True, choices=[('published', 'Published'), ('draft', 'Draft')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('preshipment', 'Pre-shipment'), ('delivered', 'Delivered'), ('unshipped', 'Unshipped'), ('shipped', 'Shipped')], max_length=50, null=True),
        ),
    ]
