# Generated by Django 4.2.2 on 2024-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_order_refund_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xl', 'XL'), ('xxs', 'XXS'), ('m', 'M'), ('xxl', 'XXL'), ('xxxl', 'XXXL'), ('xs', 'XS'), ('l', 'L'), ('s', 'S'), ('xxxs', 'XXXS')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('ft', 'Feet'), ('in', 'Inches'), ('cm', 'CM')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('4', '4'), ('2', '2'), ('1', '1'), ('3', '3'), ('5', '5')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('unshipped', 'Unshipped'), ('preshipment', 'Pre-shipment'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
