# Generated by Django 4.2.2 on 2024-03-31 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0013_alter_productsize_size_alter_productsize_size_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xxxl', 'XXXL'), ('xs', 'XS'), ('xxs', 'XXS'), ('xl', 'XL'), ('xxxs', 'XXXS'), ('l', 'L'), ('xxl', 'XXL'), ('s', 'S'), ('m', 'M')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('in', 'Inches'), ('ft', 'Feet'), ('cm', 'CM')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('1', '1'), ('2', '2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('shipped', 'Shipped'), ('unshipped', 'Unshipped'), ('preshipment', 'Pre-shipment'), ('delivered', 'Delivered')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('free_shipping', 'Free Shipping'), ('free_2_day_shipping', 'Free 2 Day Shipping'), ('free_express_shipping', 'Free Express Shipping')], max_length=70, null=True),
        ),
        migrations.CreateModel(
            name='Refunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_refund', models.TextField(blank=True, max_length=300, null=True)),
                ('refund_accepted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_for_user_ecommerce', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
