# Generated by Django 4.2.2 on 2024-03-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_productsize_size_alter_productsize_size_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xxxs', 'XXXS'), ('m', 'M'), ('xxs', 'XXS'), ('xxxl', 'XXXL'), ('xxl', 'XXL'), ('xl', 'XL'), ('s', 'S'), ('xs', 'XS'), ('l', 'L')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('in', 'Inches'), ('cm', 'CM'), ('ft', 'Feet')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('5', '5'), ('4', '4'), ('1', '1')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(blank=True, choices=[('published', 'Published'), ('draft', 'Draft')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('shipped', 'Shipped'), ('preshipment', 'Pre-shipment'), ('unshipped', 'Unshipped')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('free_express_shipping', 'Free Express Shipping'), ('free_shipping', 'Free Shipping'), ('free_2_day_shipping', 'Free 2 Day Shipping')], max_length=70, null=True),
        ),
    ]
