# Generated by Django 4.2.2 on 2024-03-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_alter_productsize_size_alter_productsize_size_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xxl', 'XXL'), ('xl', 'XL'), ('xs', 'XS'), ('xxxs', 'XXXS'), ('s', 'S'), ('xxxl', 'XXXL'), ('m', 'M'), ('l', 'L'), ('xxs', 'XXS')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('5', '5'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('unshipped', 'Unshipped'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('preshipment', 'Pre-shipment')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('free_shipping', 'Free Shipping'), ('free_express_shipping', 'Free Express Shipping'), ('free_2_day_shipping', 'Free 2 Day Shipping')], max_length=70, null=True),
        ),
    ]
