# Generated by Django 4.2.2 on 2024-04-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_alter_productsize_size_alter_reviews_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xxs', 'XXS'), ('xl', 'XL'), ('l', 'L'), ('m', 'M'), ('xxl', 'XXL'), ('xxxs', 'XXXS'), ('s', 'S'), ('xs', 'XS'), ('xxxl', 'XXXL')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('in', 'Inches'), ('ft', 'Feet'), ('cm', 'CM')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('5', '5'), ('3', '3'), ('4', '4'), ('2', '2'), ('1', '1')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('preshipment', 'Pre-shipment'), ('unshipped', 'Unshipped'), ('shipped', 'Shipped')], max_length=50, null=True),
        ),
    ]
