# Generated by Django 4.2.2 on 2024-04-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_alter_productsize_size_alter_productsize_size_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xl', 'XL'), ('xxxl', 'XXXL'), ('m', 'M'), ('xs', 'XS'), ('xxxs', 'XXXS'), ('xxl', 'XXL'), ('l', 'L'), ('s', 'S'), ('xxs', 'XXS')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('cm', 'CM'), ('in', 'Inches'), ('ft', 'Feet')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('3', '3'), ('2', '2'), ('5', '5'), ('4', '4'), ('1', '1')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(blank=True, choices=[('published', 'Published'), ('draft', 'Draft')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('unshipped', 'Unshipped'), ('preshipment', 'Pre-shipment'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
