# Generated by Django 4.2.2 on 2024-04-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_alter_productsize_size_alter_productsize_size_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('m', 'M'), ('l', 'L'), ('xxl', 'XXL'), ('xxxs', 'XXXS'), ('xs', 'XS'), ('xxs', 'XXS'), ('xxxl', 'XXXL'), ('s', 'S'), ('xl', 'XL')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('cm', 'CM'), ('ft', 'Feet'), ('in', 'Inches')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('3', '3'), ('4', '4'), ('5', '5'), ('2', '2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('preshipment', 'Pre-shipment'), ('unshipped', 'Unshipped'), ('shipped', 'Shipped')], max_length=50, null=True),
        ),
    ]
