# Generated by Django 4.2.2 on 2024-04-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_brand_brand_products_alter_productsize_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('m', 'M'), ('xxxl', 'XXXL'), ('s', 'S'), ('xl', 'XL'), ('xxs', 'XXS'), ('xs', 'XS'), ('xxl', 'XXL'), ('xxxs', 'XXXS'), ('l', 'L')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('5', '5'), ('4', '4'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('free_2_day_shipping', 'Free 2 Day Shipping'), ('free_shipping', 'Free Shipping'), ('free_express_shipping', 'Free Express Shipping')], max_length=70, null=True),
        ),
    ]
