# Generated by Django 4.2.2 on 2024-04-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_alter_productsize_size_alter_reviews_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vote',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('m', 'M'), ('xxs', 'XXS'), ('s', 'S'), ('xxl', 'XXL'), ('xxxl', 'XXXL'), ('l', 'L'), ('xxxs', 'XXXS'), ('xl', 'XL'), ('xs', 'XS')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('cm', 'CM'), ('in', 'Inches'), ('ft', 'Feet')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('5', '5'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('unshipped', 'Unshipped'), ('preshipment', 'Pre-shipment')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('free_express_shipping', 'Free Express Shipping'), ('free_2_day_shipping', 'Free 2 Day Shipping'), ('free_shipping', 'Free Shipping')], max_length=70, null=True),
        ),
    ]
