# Generated by Django 4.2.2 on 2024-04-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_alter_productsize_size_alter_productsize_size_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarks',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xxxl', 'XXXL'), ('xxxs', 'XXXS'), ('l', 'L'), ('s', 'S'), ('xxl', 'XXL'), ('m', 'M'), ('xl', 'XL'), ('xxs', 'XXS'), ('xs', 'XS')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('cm', 'CM'), ('in', 'Inches'), ('ft', 'Feet')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('1', '1'), ('2', '2'), ('5', '5')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('preshipment', 'Pre-shipment'), ('unshipped', 'Unshipped'), ('shipped', 'Shipped')], max_length=50, null=True),
        ),
    ]
