# Generated by Django 4.2.2 on 2024-04-03 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0026_rename_product_bookmarks_products_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmarks',
            new_name='Bookmark',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('xl', 'XL'), ('xxs', 'XXS'), ('xxl', 'XXL'), ('m', 'M'), ('xxxl', 'XXXL'), ('xxxs', 'XXXS'), ('l', 'L')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(blank=True, choices=[('ft', 'Feet'), ('cm', 'CM'), ('in', 'Inches')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('5', '5'), ('3', '3'), ('4', '4'), ('2', '2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('preshipment', 'Pre-shipment'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('unshipped', 'Unshipped')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('free_shipping', 'Free Shipping'), ('free_2_day_shipping', 'Free 2 Day Shipping'), ('free_express_shipping', 'Free Express Shipping')], max_length=70, null=True),
        ),
    ]
