# Generated by Django 4.2.2 on 2024-03-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(blank=True, choices=[('starter', 'Starter'), ('vendor_account', 'Vendor account'), ('dropshipper_account', 'Dropshipper account'), ('vendor_and_dropshipper', 'Vendor and dropshipper')], max_length=300, null=True),
        ),
    ]
