# Generated by Django 4.2.2 on 2024-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_mp_app', '0003_orderitem_user_alter_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
