# Generated by Django 4.2.2 on 2024-03-31 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_remove_taxrate_slug_remove_taxrate_title_and_more'),
        ('ds_mp_app', '0004_alter_order_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.taxrate'),
        ),
    ]
