# Generated by Django 4.2.2 on 2024-03-31 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ds_mp_app', '0005_order_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropshipFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('dropship_fee_rate', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='dropship_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ds_mp_app.dropshipfeesettings'),
        ),
    ]
