# Generated by Django 4.2.2 on 2024-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_mp_app', '0006_dropshipfeesettings_order_dropship_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested_proccessed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
