# Generated by Django 4.2.2 on 2024-03-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_mp_app', '0009_order_billing_address_order_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunds',
            name='refund_request_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
