# Generated by Django 4.2.2 on 2024-03-31 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ds_mp_app', '0010_refunds_refund_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunds',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
