# Generated by Django 4.2.2 on 2024-04-01 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_title', models.CharField(max_length=100)),
                ('vendor_descripton', models.TextField(blank=True, max_length=2000, null=True)),
                ('vendor_logo', models.ImageField(blank=True, default='media/DS_MP_APP/VENDORS/VENDORS_LOGOS/default.jpg', null=True, upload_to='media/DS_MP_APP/VENDORS/VENDORS_LOGOS/')),
                ('vendor_cover_image', models.ImageField(blank=True, default='media/DS_MP_APP/VENDORS/VENDORS_LOGOS/cover-image-default.jpg', null=True, upload_to='media/DS_MP_APP/VENDORS/VENDORS_COVER_IMAGES/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
