# Generated by Django 4.2.2 on 2024-04-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_alter_productsize_size_alter_productsize_size_label_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_products',
            field=models.ManyToManyField(blank=True, null=True, to='ecommerce.product'),
        ),
    ]
