# Generated by Django 4.2.2 on 2024-04-01 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_alter_productsize_size_alter_productsize_size_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0002_vendorprofile_vendor_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_title', models.CharField(max_length=100)),
                ('vendor_descripton', models.TextField(blank=True, max_length=2000, null=True)),
                ('vendor_logo', models.ImageField(blank=True, default='media/DS_MP_APP/VENDORS/VENDORS_LOGOS/default.jpg', null=True, upload_to='media/DS_MP_APP/VENDORS/VENDORS_LOGOS/')),
                ('vendor_cover_image', models.ImageField(blank=True, default='media/DS_MP_APP/VENDORS/VENDORS_LOGOS/cover-image-default.jpg', null=True, upload_to='media/DS_MP_APP/VENDORS/VENDORS_COVER_IMAGES/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ds_mp_vendor', to=settings.AUTH_USER_MODEL)),
                ('vendor_products', models.ManyToManyField(blank=True, null=True, to='ecommerce.product')),
            ],
        ),
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
